apiVersion: v1
kind: Service
metadata:
  name: neo4jsvc  
spec:
  type: NodePort
  ports:
  - port: 7474
    nodePort: 30080
    name: http
  - port: 7473
    nodePort: 30443
    name: https
  - port: 7687
    nodePort: 32687
    name: bolt
